#!/usr/bin/env bash
#culori grase
negru='\E[1;30m' rosu='\e[1;31m' verde='\e[1;32m' verdef='\e[0;30;42m' galben='\e[1;33m' albastru='\e[1;34m' purpuriu='\e[1;35m' cyan='\e[1;36m' alb='\e[1;37m' esc='\e[0m'
while :;do
while :;do
clear
echo -e $purpuriu "_____  _   _  _   _    _    _   _  ___ ";echo  ")__ __(\ ( ) /) \_/ (  )_\  ) ( ) () __("
echo  "  | |   )\_/( |  _  | /( )\  ) | ( | _) ";echo  "  )_(    \_/  )_( )_()_/ \_()_( )_()___(";echo;echo "              ___  __    ____ ";echo "             / __)(  )  (_  _)";echo "            ( (__  )(__  _)(_ ";echo "             \___)(____)(____)";echo
testconnection=`wget --tries=3 --timeout=15 www.google.com -qO - &>/dev/null 2>&1`
if [ $? != 0 ]; then for i in `seq 1 2`;do 
clear;sleep 1;echo -e $rosu "! Verificati conexiunea la internet !"$esc;sleep 1;done; exit 1;fi;
consola(){
consola=`echo $DISPLAY'a'`
if [[ "$consola" = "a" ]]; then
echo -e $purpuriu"Introduceti marimea ferestrei si coordonatele de redare"$rosu "(ex. 360 10:10)" $verde
read marime coordonate
else
marime=360
coordonate=10:20
fi
}
mkdir -p $HOME/'.'tvmaxe-cli
if [ ! -f $HOME/.tvmaxe-cli/subscrieri ];then wget -qO - https://raw.github.com/nknwn/tvmaxe-cli/master/.subscrieri > $HOME/.tvmaxe-cli/subscrieri;fi
if [ ! -f $HOME/.tvmaxe-cli/.commit_tv ];then wget -qO - https://github.com/nknwn/tvmaxe-cli|grep '"sha"'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $5}' > $HOME/.tvmaxe-cli/.commit_tv; fi;
if [ -f $HOME/.tvmaxe-cli/.commit_tv ]; then
commit1=`wget -qO - https://github.com/nknwn/tvmaxe-cli|grep '"sha"'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $5}'`
commit2=`cat $HOME/.tvmaxe-cli/.commit_tv|sed -n '$p'`
echo v.0.3.9b commit: `cat $HOME/.tvmaxe-cli/.commit_tv|sed -n '$p'`;echo
if [[ "$commit1" != "$commit2" ]]; then 
wget -qO - https://github.com/nknwn/tvmaxe-cli|grep '"sha"'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $5}' > $HOME/.tvmaxe-cli/.commit_tv
echo -e $rosu"Actualizare: "$cyan http://nknwn.github.com/tvmaxe-cli/ $rosu
echo -e Pentru a actuaiza doar tvmaxe-cli alegeti '"a"', pentru a actualiza si subscrierile alegeti '"as"'
echo -e Atentie! actualizarea '"as"' presupune suprascrierea fisierului '"subscrieri"'$purpuriu;wget -qO - http://pastebin.com/raw.php?i=zadMXuWU;echo
fi;fi;
cat $HOME/.tvmaxe-cli/subscrieri|sed -n '$p'|sed 's/||/\n /g'|awk '{print $1}'|nl|column -c 30|column -t|more -d
echo -e $cyan"Alegeti numarul subscrierii dorite:" $cyan "sau parasiti " $rosu"q"$cyan"uit"$rosu
read sursa
if [[ "$sursa" = "q" ]];then exit 0; fi;
if [[ "$sursa" = "a" ]];then 
su -c 'wget -qO - https://raw.github.com/nknwn/tvmaxe-cli/master/tvmaxe-cli > /usr/bin/tvmaxe-cli';exit 0;fi;
if [[ "$sursa" = "as" ]];then
wget -qO - https://raw.github.com/nknwn/tvmaxe-cli/master/.subscrieri > $HOME/.subscrieri
su -c 'wget -qO - https://raw.github.com/nknwn/tvmaxe-cli/master/tvmaxe-cli > /usr/bin/tvmaxe-cli';exit 0;fi;
sur=`cat $HOME/.tvmaxe-cli/subscrieri|sed -n '$p'|sed 's/||/\n /g'|awk '{print $2}'|sed -n "${sursa}p"`
if [[ "$sur" = "filme" ]];then
while :;do
while :;do
clear
echo -e $purpuriu Filme si seriale noi: www.990.ro$verde
wget -qO - http://www.990.ro|sed -n '/border:1/,/clear:/ p'|grep title|sed 's/<[^>]*>/ /g;s/^[ \t]*//;s/[ \t]*$//'|nl|more -d
echo -e $purpuriu Selectati numarul filmului dorit sau $rosu"c"$purpuriu"autati" altul";" $rosu"r"$purpuriu"eveniti"";"$rosu "q"$purpuriu"uit"$rosu
read noutate
if [[ "$noutate" = "r" ]]; then break 3;fi;
if [[ "$noutate" = "q" ]]; then exit 0;fi;
###############################################################
if [[ "$noutate" = *[[:digit:]]* ]];then
adresa=`wget -qO - http://www.990.ro|sed -n '/border:1/,/clear:/ p'|grep title|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'|sed -n "${noutate}p"`
server1=`wget -qO - http://www.990.ro/$adresa|grep Fastupload|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'|sed 's/:/ /g'|awk '{print "http:"$3'}`
#server2=`wget -qO - http://www.990.ro/$adresa|grep 180upload|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'|sed 's/:/ /g'|awk '{print "http:"$3'}`
nume=`wget -qO - http://www.990.ro|sed -n '/border:1/,/clear:/ p'|grep title|sed 's/<[^>]*>/ /g;s/^[ \t]*//;s/[ \t]*$//;s/ /_/g'|sed -n "${noutate}p"`
descriere=`wget -qO - http://www.990.ro/$adresa|sed -n "/colspan='2'/,/\/blockquote/ p"|sed 's/<[^>]*>/ /g'`
#################################################################
upload=`wget -qO - $server1|grep fastupload|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'`
#upload1=`wget -qO - $server2|grep 180upload|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
################################################################
fi;
echo -e $verde
###############################################################
if [[ "$noutate" = "c" ]]; then read -p "Ce film cautam? " titlu
wget -qO - "http://www.990.ro/cauta2.php?text=$titlu&submit=Cauta"|sed -n '/content_wrapper/,/post_title/ p'|grep titlu|sed 's/ /_/g;s/[<>"]/ /g'|awk '{print $5,$3,"Gasit_pe:_www.990.ro"}'>/tmp/caut
#wget -qO - http://cinemaxx.ro/search.php?keywords=$titlu|sed -n '/browse_results/,/laquo/ p'|grep 'href\|scr'|sed 's/ /_/g;s/"/ /g' >> /tmp/caut
wget -qO - http://filmehd.net/?s=$titlu|sed -n '/search-movies/,/content / p'|grep jpg|sed 's/ /_/g;s/[";]/ /g;s/\&#8211//g;s/\&#039//g'|awk '{print $6,$4,"Gasit_pe:_filmehd.net"}'>>/tmp/caut
>> /tmp/caut
wget -qO - http://www.filmeonline.org/search/$titlu/|grep bookmark|sed 's/ /_/g;s/"/ /g'|awk '{print $8,$4,"Gasit_pe:_www.filmeonline.org"}'>>/tmp/caut
wget -qO - http://www.filmeonlinefree.net/?s=$titlu|sed -n '/content start/,/content end/ p'|grep del.icio|sed 's/ /_/g;s/["=&]/ /g'|awk '{print $5,$3,"Gasit_pe:_www.filmeonlinefree.net"}'>>/tmp/caut
###############################################################
if [[ -z `cat /tmp/caut` ]]; then clear
for i in `seq 1 2`;do
sleep 1;echo -e $rosu"Nu am gasit filmul cautat sau posibil sa fi gresit denumirea? mai incercati..." 
sleep 1;clear;done;break;
else
cat /tmp/caut|awk '{print $1,$3}'|column -t|sed 's/_/ /g'|nl|more -d
fi;
###############################################################
echo -e $purpuriu Selectati numarul filmului dorit sau $rosu"c"$purpuriu"autati" altul";" $rosu"r"$purpuriu"eveniti"";"$rosu "q"$purpuriu"uit"$verde
read numar
if [[ "$numar" = "r" ]];then break 3;fi;
if [[ "$numar" = "c" ]];then break;fi;
if [[ "$numar" = "q" ]];then exit 0;fi;
sursa=`cat /tmp/caut|awk '{print $3}'|sed 's/_/ /g'|awk '{print $3}'|sed -n "${numar}p"`
adresa2=`cat /tmp/caut|awk '{print $2}'|sed -n "${numar}p"`
nume=`cat /tmp/caut|awk '{print $1}'|sed -n "${numar}p"`
if [[ "$sursa" = "www.990.ro" ]];then
selectie=`echo $adresa2|sed 's/-/ /g'|awk '{print $1}'`
if [[ "$selectie" = "filme" ]]; then
server1=`wget -qO - http://www.990.ro/$adresa2|grep Fastupload|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'|sed 's/:/ /g'|awk '{print "http:"$3'}`
#server2=`wget -qO - http://www.990.ro/$adresa2|grep 180upload|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'|sed 's/:/ /g'|awk '{print "http:"$3'}`
descriere=`wget -qO - http://www.990.ro/$adresa2|sed -n "/colspan='2'/,/\/blockquote/ p"|sed "s/<[^>]*>/ /g;s/:/\n/"`
fi
#################################################################
if [[ "$selectie" = "seriale" ]]; then
wget -qO - http://www.990.ro/$adresa2|sed -n '/show_faces/,/sidebar_wrapper/ p'|grep href|sed "s/px;/\n/g;s/ /_/g;s/[><']/ /g"|grep href|awk '{print $1,$7}'|column -t|sed 's/_/ /g'|nl|more -d
echo -e $purpuriu Selectati numarul filmului dorit sau $rosu"c"$purpuriu"autati" altul";" $rosu"r"$purpuriu"eveniti"";"$rosu "q"$purpuriu"uit"$verde
read nr
if [[ "$nr" = "r" ]];then break 3;fi;
if [[ "$nr" = "c" ]];then break;fi;
if [[ "$nr" = "q" ]];then exit 0;fi;
sezoane=`wget -qO - http://www.990.ro/$adresa2|sed -n '/show_faces/,/sidebar_wrapper/ p'|grep href|sed "s/px;/\n/g;s/ /_/g;s/[><']/ /g"|grep href|awk '{print $6}'|sed -n "${nr}p"`
nume=`wget -qO - http://www.990.ro/$adresa2|sed -n '/show_faces/,/sidebar_wrapper/ p'|grep href|sed "s/px;/\n/g;s/ /_/g;s/[><']/ /g"|grep href|awk '{print $7}'|sed -n "${nr}p"`
descriere=`wget -qO - http://www.990.ro/$adresa2|sed -n "/colspan='2'/,/\/blockquote/ p"|sed "s/<[^>]*>/ /g;s/:/\n/g"`
server1=`wget -qO - http://www.990.ro/$sezoane|grep Fastupload|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'|sed 's/:/ /g'|awk '{print "http:"$3'}`
#server2=`wget -qO - http://www.990.ro/$sezoane|grep 180upload|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'|sed 's/:/ /g'|awk '{print "http:"$3'}`
fi;
#################################################################
upload=`wget -qO - $server1|grep fastupload|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'`
#upload1=`wget -qO - $server2|grep 180upload|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
################################################################
fi;fi
if [[ "$sursa" = "filmehd.net" ]];then
upload=`wget -qO - $adresa2|grep vk|sed 's/ /_/g;s/"/ /g;s/amp;//g'|awk '{print $2}'`
descriere=`wget -qO - $adresa2|grep og:description|sed 's/ /_/g;s/"/ /g'|awk '{print $4}'|sed 's/_/ /g'`
wget -qO - "$upload"|sed -n '/video_host/,/video_vtag/ p'|sed "s/ /_/g;s/'/ /g"|awk '{print $2}' > /tmp/surse
fi;
if [[ "$sursa" = "www.filmeonline.org" ]];then
upload=`wget -qO - $adresa2|grep VK|sed 's/ /_/g;s/"/ /g;s/?/ /g;s/\;/\&/g;s/\#038//g'|sed -n '1p'|awk '{print $3}'`
wget -qO - "http://vk.com/video_ext.php?$upload"|sed -n '/video_host/,/video_vtag/ p'|sed "s/ /_/g;s/'/ /g"|awk '{print $2}' > /tmp/surse
descriere=`wget -qO - $adresa2|sed -n '/itemprop/,/more-/ p'|sed 's/<[^>]*>/ /g'`
#are si fastupload
fi;
if [[ "$sursa" = "www.filmeonlinefree.net" ]];then
upload=`wget -qO - $adresa2|grep vk|sed 's/ /_/g;s/"/ /g;s/\;/\&/g'|awk '{print $4}'`
wget -qO - "$upload"|sed -n '/video_host/,/video_vtag/ p'|sed "s/ /_/g;s/'/ /g"|awk '{print $2}' > /tmp/surse
descriere=`wget -qO - $adresa2|sed -n '/entry4/,/\.</ p'|sed 's/<[^>]*>/ /g'`
fi;
filtru=`wget -qO - $upload|grep "fastupload.ro"`
if [[ -z $filtru ]];then
host=`cat /tmp/surse|sed -n '1p'`
uid=`cat /tmp/surse|sed -n '2p'`
vtag=`cat /tmp/surse|sed -n '3p'`
rez=.240
ext=.mp4
film1="$host"u$uid/video/$vtag$rez$ext
else
film1=`wget -qO - $upload|grep flv|sed "s/ /_/;s/'/ /g"|awk '{print $4}'`
#film2=`wget -qO - $upload1|grep "video|"|sed 's/ /_/g;s/|/ /g'|awk '{print "http://"$10"."$9"."$8"."$7":"$20"/d/"$19"/video.flv"}'`
ext=.flv
fi;
################################################################
testfilm=`wget --spider $film1 -qO - &>/dev/null 2>&1`
if [ $? != 0 ]; then for i in `seq 1 2`;do 
clear;sleep 1;echo -e $rosu "! Se pare ca fisierul nu mai exista !"$verde;sleep 1;done;break;fi;
################################################################
echo -e $verdef$nume$esc
echo -e $verde$descriere
################################################################
echo -e $purpuriu
OPTIUNE="Redati Descarcati Inregistrati Cautati Reveniti Parasiti"
select opt in $OPTIUNE;do
if [[ "$opt" = "Redati" ]]; then clear
consola
echo -e $verde"Redau:" $verdef$nume...$esc
mplayer -cache 1000 -hardframedrop -cache-min 20 -msglevel cache=-1 -prefer-ipv4 -msgcolor -nolirc -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry $coordonate -nobps -ni -forceidx -mc 0 $film1 &>/dev/null
clear;echo -e $verde"Ati vizionat: "$verdef$nume$esc;sleep 3;break
elif [[ "$opt" = "Descarcati" ]]; then axel -a -o $HOME/$nume$ext $film1||wget -O $HOME/$nume$ext --progress=dot $film1 2>&1 |grep --line-buffered "%" | sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}' 
echo -ne "\b\b\b\b";break
elif [[ "$opt" = "Cautati" ]];then clear; break;
elif [[ "$opt" = "Reveniti" ]];then break 4;
elif [[ "$opt" = "Inregistrati" ]]; then clear
consola
echo -e $verde"Inregistrez:" $verdef$nume...$esc
$(wget -O $HOME/$nume$ext $film1 &>/dev/null &);echo -e $rosu"...redarea va incepe in 10 sec" $purpuriu; sleep 10 ; wait $(mplayer -cache 1000 -hardframedrop -cache-min 20 -msglevel cache=-1 -prefer-ipv4 -msgcolor -nolirc -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry $coordonate  -osdlevel 2 $HOME/$nume$ext &>/dev/null); killall wget;
clear;echo -e $verde"Ati vizionat: "$verdef$nume$esc;sleep 3;break
echo -e $cyan"Doriti sa pastrati inregistrarea"$verde" y/n"$cyan"?"
read rec
if  [[ "$rec" = "n" ]]; then rm $HOME/$nume$ext; exit 0;else break 4;fi;
elif [[ "$opt" = "Parasiti" ]]; then exit 0;
else echo -e $rosu Ati ales gresit, mai incercati. $esc
fi;done;done;done;fi
#########################################################
if [[ "$sur" = "youtube" ]];then
i=1
while :;do
while :;do
clear
echo -e $purpuriu"Introduceti numele piesei dorite sau redati o" $rosu"l"$purpuriu"ista" existenta, $rosu"r"$purpuriu"eveniti"";"$rosu "q"$purpuriu"uit"$rosu
read titlu
if [[ "$titlu" = "r" ]];then break 3;fi;
if [[ "$titlu" = "q" ]];then exit 0;fi;
if [[ "$titlu" = "l" ]];then clear
echo -e $purpuriu"Liste existente:"$verde
ls $HOME/.tvmaxe-cli/playlist/|nl
echo -e $purpuriu"Alegeti lista pentru redare:"$verde
read pl;clear
lista=`ls $HOME/.tvmaxe-cli/playlist/|sed -n "${pl}p"`
echo -e $verdef $lista $esc $verde
fisier=`ls $HOME/.tvmaxe-cli/playlist/|sed -n "${pl}p"`
piesepl=`cat $HOME/.tvmaxe-cli/playlist/$fisier|wc -l`
OPTIUNE="Redati Redati_audio Descarcati_lista Conversie_mp3 Stergeti_lista Reveniti Parasiti"
select opt in $OPTIUNE; do
if [[ "$opt" = "Redati" ]];then clear
consola
for p in `seq 1 $piesepl` ; do
echo -e $verdef $lista $esc $verde
cat $HOME/.tvmaxe-cli/playlist/$lista|awk '{print $2}'|sed 's/_/ /g'|nl
adresa=`cat $HOME/.tvmaxe-cli/playlist/$fisier|sed -n "${p}p"`
nume=`wget -qO - "$adresa"|grep eow-title|sed 's/ /_/g;s/"/ /g'|awk '{print $8}'`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http > /tmp/yt
piesa=`cat /tmp/yt`
echo -e Redau $verdef $(( i++ )). $nume...$esc $verde
mplayer -cache 500 -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry  $coordonate -osdlevel 3 $piesa &>/dev/null
clear;done; break;
elif [[ "$opt" = "Redati_audio" ]];then clear
for p in `seq 1 $piesepl` ; do
cat $HOME/.tvmaxe-cli/playlist/$lista|awk '{print $2}'|sed 's/_/ /g'|nl
adresa=`cat $HOME/.tvmaxe-cli/playlist/$fisier|sed -n "${p}p"`
nume=`wget -qO - "$adresa"|grep eow-title|sed 's/ /_/g;s/"/ /g'|awk '{print $8}'`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http > /tmp/yt
piesa=`cat /tmp/yt`
echo -e Redau $verdef  $(( i++ )). $nume...$esc $verde
mplayer -cache 500 -ao alsa -novideo $piesa &>/dev/null
clear;done; break;
elif [[ "$opt" = "Descarcati_lista" ]]; then clear
for p in `seq 1 $piesepl` ; do
cat $HOME/.tvmaxe-cli/playlist/$lista|awk '{print $2}'|sed 's/_/ /g'|nl
adresa=`cat $HOME/.tvmaxe-cli/playlist/$fisier|sed -n "${p}p"`
nume=`wget -qO - "$adresa"|grep eow-title|sed 's/ /_/g;s/"/ /g'|awk '{print $8}'`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http > /tmp/yt
piesa=`cat /tmp/yt`
echo -e Descarc $verdef  $(( i++ )). $nume...$esc $verde
wget -O $HOME/$nume.flv --progress=dot $piesa 2>&1 |grep --line-buffered "%" | sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}' 
echo -ne "\b\b\b\b"
clear;done; break;
elif [[ "$opt" = "Conversie_mp3" ]];then clear
for p in `seq 1 $piesepl` ; do
cat $HOME/.tvmaxe-cli/playlist/$lista|awk '{print $2}'|sed 's/_/ /g'|nl
adresa=`cat $HOME/.tvmaxe-cli/playlist/$fisier|sed -n "${p}p"`
nume=`wget -qO - "$adresa"|grep eow-title|sed 's/ /_/g;s/"/ /g'|awk '{print $8}'`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http > /tmp/yt
piesa=`cat /tmp/yt`
echo -e Conversie $verdef  $(( i++ )). $nume...$esc $verde
echo
echo -e $verdef"Descarc... fisierul flv"$esc$rosu
wget -O /tmp/$nume.flv --progress=dot $piesa 2>&1 |grep --line-buffered "%" | sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}' 
echo -ne "\b\b\b\b"
echo
echo -e $verdef"Conversie... flv>wav"$esc$rosu
sleep 1
mplayer -novideo -nocorrect-pts -ao pcm:waveheader /tmp/$nume.flv &>/dev/null
echo
echo -e $verdef"Conversie... wav>mp3"$esc$rosu
lame -h -b 192 audiodump.wav $HOME/$nume.mp3
sleep 1
echo -e $verdef"Sterg fisierele flv si wav"$esc$verde
rm $HOME/audiodump.wav /tmp/$nume.flv
clear;done;break

elif [[ "$opt" = "Stergeti_lista" ]]; then rm $HOME/.tvmaxe-cli/playlist/$fisier
break
elif [[ "$opt" = "Reveniti" ]];then break 2;
elif [[ "$opt" = "Parasiti" ]]; then exit;
else echo -e $rosu"Ati ales gresit, mai incercati." $esc
fi;done;fi;
pagini=`wget -qO -  http://www.youtube.com/results?search_query="$titlu"|grep data-page|wc -l`
> /tmp/yt
for a in `seq 1 $pagini` ; do
wget -qO - "http://www.youtube.com/results?search_query='$titlu'&page=$a"|grep item-title|grep video|sed 's/ /_/g;s/"/ /g'|sed 's/\&amp;quot;//g'|awk '{print $4,"http://www.youtube.com/watch?v="$12,$10,$8}' >> /tmp/yt
done
echo -e $verde
cat /tmp/yt|awk '{print $1}'|nl|column -t|sed 's/_/ /g;s/\&lt;b&gt;//g'|sed 's/\#39//g'|sed 's/&amp//'|more -d
echo -e $purpuriu"Selectati numarul pieselor dorite pentru redare, redati $rosu"t"$purpuriu"oate," "$rosu"c"$purpuriu"autati" altele";" $rosu"r"$purpuriu"eveniti"";"$rosu "q"$purpuriu"uit"$verde
read nr
if [[ "$nr" = "r" ]];then break 3;fi;
if [[ "$nr" = "c" ]];then break;fi;
if [[ "$nr" = "q" ]];then exit 0;fi;
if [[ "$nr" = "t" ]];then
piesepl=`cat /tmp/yt|wc -l`
consola
echo $piesepl
for p in `seq 1 $piesepl` ; do
adresa=`cat /tmp/yt|awk '{print $2}'|sed -n "${p}p"`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http >> /tmp/yt
cat /tmp/yt|awk '{print "|Nume: "$1,"| Utilizator: "$3,"| Durata: "$4"|"}'|sed 's/_/ /g'|sed -n "${p}p"
piesa=`cat /tmp/yt|sed -n '$p'`
nume1=`cat /tmp/yt|awk '{print $1}'|sed 's/_/ /g'|sed -n "${p}p"`
testpiesa=`wget --spider $piesa -qO - &>/dev/null 2>&1`
if [ $? != 0 ]; then for i in `seq 1 2`;do 
clear;sleep 1;echo -e $rosu"! Se pare ca fisierul nu mai exista sau necesita autentificare!"$verde;sleep 1;done;
else
echo -e $verde"Redau: "$verdef $nume1... $esc $verde
mplayer -cache 500 -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry  $coordonate  -osdlevel 3 $piesa &>/dev/null
fi;done;break;fi;
echo
OPTIUNE="Redati Redati_audio Descarcati Conversie_mp3 Playlist Reveniti Parasiti"
select opt in $OPTIUNE;do
if [[ "$opt" = "Redati" ]];then
consola
clear
for p in $nr ; do
adresa=`cat /tmp/yt|awk '{print $2}'|sed -n "${p}p"`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http >> /tmp/yt
cat /tmp/yt|awk '{print "|Nume: "$1,"| Utilizator: "$3,"| Durata: "$4"|"}'|sed 's/_/ /g'|sed -n "${p}p"
piesa=`cat /tmp/yt|sed -n '$p'`
nume1=`cat /tmp/yt|awk '{print $1}'|sed 's/_/ /g'|sed -n "${p}p"`
testpiesa=`wget --spider $piesa -qO - &>/dev/null 2>&1`
if [ $? != 0 ]; then for i in `seq 1 2`;do 
clear;sleep 1;echo -e $rosu"! Se pare ca fisierul nu mai exista sau necesita autentificare!"$verde;sleep 1;done;
else
echo -e $verde"Redau: "$verdef $nume1... $esc $verde
mplayer -cache 500 -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry  $coordonate  -osdlevel 3 $piesa &>/dev/null
fi;done; break
elif [[ "$opt" = "Redati_audio" ]];then clear
for p in $nr ; do
adresa=`cat /tmp/yt|awk '{print $2}'|sed -n "${p}p"`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http >> /tmp/yt
cat /tmp/yt|awk '{print "|Nume: "$1,"| Utilizator: "$3,"| Durata: "$4"|"}'|sed 's/_/ /g'|sed -n "${p}p"
piesa=`cat /tmp/yt|sed -n '$p'`
nume1=`cat /tmp/yt|awk '{print $1}'|sed 's/_/ /g'|sed -n "${p}p"`
testpiesa=`wget --spider $piesa -qO - &>/dev/null 2>&1`
if [ $? != 0 ]; then for i in `seq 1 2`;do 
clear;sleep 1;echo -e $rosu"! Se pare ca fisierul nu mai exista sau necesita autentificare!"$verde;sleep 1;done;
else
echo -e $verde"Redau: "$verdef $nume1...$esc $verde
mplayer -novideo -ao alsa $piesa &>/dev/null;fi;done;break
elif [[ "$opt" = "Descarcati" ]];then
for p in $nr ; do
adresa=`cat /tmp/yt|awk '{print $2}'|sed -n "${p}p"`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http >> /tmp/yt
cat /tmp/yt|awk '{print "|Nume: "$1,"| Utilizator: "$3,"| Durata: "$4"|"}'|sed 's/_/ /g'|sed -n "${p}p"
piesa=`cat /tmp/yt|sed -n '$p'`
nume=`cat /tmp/yt|awk '{print $1}'|sed -n "${p}p"`.flv
testpiesa=`wget --spider $piesa -qO - &>/dev/null 2>&1`
if [ $? != 0 ]; then for i in `seq 1 2`;do 
clear;sleep 1;echo -e $rosu "! Se pare ca fisierul nu mai exista sau necesita autentificare!"$verde;sleep 1;done;
else
echo -e Descarc $verdef  $(( i++ )). $nume...$esc $verde
wget -O $HOME/$nume --progress=dot $piesa 2>&1 |grep --line-buffered "%" | sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}' 
echo -ne "\b\b\b\b"
fi;done;break
elif [[ "$opt" = "Conversie_mp3" ]];then
for p in $nr ; do
adresa=`cat /tmp/yt|awk '{print $2}'|sed -n "${p}p"`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http >> /tmp/yt
cat /tmp/yt|awk '{print "|Nume: "$1,"| Utilizator: "$3,"| Durata: "$4"|"}'|sed 's/_/ /g'|sed -n "${p}p"
piesa=`cat /tmp/yt|sed -n '$p'`
nume=`cat /tmp/yt|awk '{print $1}'|sed -n "${p}p"`
testpiesa=`wget --spider $piesa -qO - &>/dev/null 2>&1`
if [ $? != 0 ]; then for i in `seq 1 2`;do 
clear;sleep 1;echo -e $rosu "! Se pare ca fisierul nu mai exista sau necesita autentificare!"$verde;sleep 1;done;
else
echo -e $verdef"Descarc fisierul flv"$esc
wget -O /tmp/$nume.flv --progress=dot $piesa 2>&1 |grep --line-buffered "%" | sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}' 
echo -ne "\b\b\b\b"
echo -e $verdef"Conversie in wav"$esc
mplayer -novideo -nocorrect-pts -ao pcm:waveheader /tmp/$nume.flv &>/dev/null
echo -e $verdef"Conversie in mp3"$esc
lame -h -b 192 audiodump.wav $HOME/$nume.mp3
rm $HOME/audiodump.wav /tmp/$nume.flv
fi;done;break
elif [[ "$opt" = "Playlist" ]];then
echo -e $verde "Liste existente: "
mkdir -p $HOME/'.'tvmaxe-cli/playlist/
ls $HOME/'.'tvmaxe-cli/playlist/
read -p "Indicati lista sau creati una noua: " lista
echo -e $rosu"Salvez lista..."
for p in $nr ; do
adresa=`cat /tmp/yt|awk '{print $2,$1}'|sed -n "${p}p"`
wget -qO - "$adresa"|grep signature|sed 's/ /_/g;s/%2F/\//g;s/\\//g;s/%F/?/g;s/%3D/=/g;s/%26/\&/g;s/%25/%/g;s/%3F/?/g;s/%3A/:/g;s/"/ /g;s/\u0026/\&/g;s/\generate_204/videoplayback/g'|awk '{print $4}'|grep http >> /tmp/yt
echo $adresa >> $HOME/'.'tvmaxe-cli/playlist/$lista.pl
done;break;
elif [[ "$opt" = "Reveniti" ]];then break 2;
elif [[ "$opt" = "Parasiti" ]];then exit;
else echo -e $rosu"Ati ales gresit, mai incercati."$esc
fi;done;
done;done;fi;
#########################################################
if [[ "$sur" = "divertisment" ]];then
while :;do
while :;do
clear;echo -e $purpuriu www.220.ro/funny/top-saptamana-votate/$verde
wget -qO - http://www.220.ro/funny/top-saptamana-votate/|grep data-href|grep title|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'|nl
echo -e $purpuriu Selectati numarul filmului dorit sau $rosu"c"$purpuriu"autati" altul";" $rosu"r"$purpuriu"eveniti"";"$rosu "q"$purpuriu"uit"$verde
read nr
if [[ "$nr" = *[[:digit:]]* ]];then
nume=`wget -qO - http://www.220.ro/funny/top-saptamana-votate/|grep data-href|grep title|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'|sed -n "${nr}p"`.mp4
adresa=`wget -qO -  http://www.220.ro/funny/top-saptamana-votate/|grep data-href|grep title|sed 's/ /_/g;s/"/ /g'|awk '{print $4}'|sed -n "${nr}p"`
funny=`wget -qO - $adresa|grep source|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'`
fi;
if [[ "$nr" = "r" ]];then break 3;fi;
if [[ "$nr" = "q" ]];then exit 0;fi;
if [[ "$nr" = "c" ]];then
read -p "Ce cautam? " titlu
wget -qO - http://www.220.ro/cauta/$titlu|sed -n '/cauta utilizatori/,/search_b/ p'|grep href|grep th_160|sed 's/ /_/g;s/"/ /g'|awk '{print $4,$2}' >/tmp/caut
cat /tmp/caut|awk '{print $1}'|nl
echo -e $purpuriu Selectati numarul filmului dorit sau $rosu"c"$purpuriu"autati" altul";" $rosu"r"$purpuriu"eveniti"";"$rosu "q"$purpuriu"uit"$verde
read nr1
if [[ "$nr1" = "r" ]];then break 3;fi;
if [[ "$nr1" = "c" ]];then break;fi;
if [[ "$nr1" = "q" ]];then exit 0;fi;
nume=`cat /tmp/caut|awk '{print $1}'|sed -n "${nr1}p"`.mp4
adresa1=`cat /tmp/caut|awk '{print $2}'|sed -n "${nr1}p"`
funny=`wget -qO - $adresa1|grep source|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'`
fi;
OPTIUNE="Redati Descarcati Reveniti Parasiti"
select opt in $OPTIUNE;do
if [[ "$opt" = "Redati" ]];then clear
consola
mplayer -cache 500 -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry  $coordonate  -osdlevel 3 "$funny" &>/dev/null;break
elif [[ "$opt" = "Descarcati" ]];then clear
echo -e "Descarc..." $verdef$nume$esc$verde
wget -O $HOME/$nume --progress=dot $funny 2>&1 |grep --line-buffered "%" | sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}' 
echo -ne "\b\b\b\b";break
elif [[ "$opt" = "Reveniti" ]];then break 2;
elif [[ "$opt" = "Parasiti" ]];then exit;
else echo -e $rosu"Ati ales gresit, mai incercati."$esc
fi;done;done;done;fi
#########################################################
consola=`echo $DISPLAY'a'`
echo -e $verde "Lista canale:"
if [[ "$consola" = "a" ]];then 
if [[ "$sur" = "cooltv" ]];then
wget -qO - http://www.cool-tv.ro/m/|grep sop|sed 's/ /_/g;s/"/ /g;s/.gif//'|awk '{print $4}'|sed 's/^...//;$d;s/-/_/g'|nl|column -c 30|column -t|more -d
else
wget -qO - $sur|sed 's/||/\n /g;s/ /_/g;s/|/ /g'|sed '1d'|awk '{print $2}'|nl|column -c 30|column -t|sed 's/â/a/g;s/ă/a/g;s/ț/t/g;s/ș/s/g;s/î/i/g'|more -d
fi;
echo -e $rosu "Introduceti marimea ferestrei de redare si coordonatele acesteia (ex. 360 10:10) "
echo -e $rosu "in caz ca acesta este un post radio alegeti orice valoare (ex. 1 1)"
read marime coordonate
else
marime=360
coordonate=10:20
if [[ "$sur" = "cooltv" ]];then
wget -qO - http://www.cool-tv.ro/m/|grep sop|sed 's/ /_/g;s/"/ /g;s/.gif//'|awk '{print $4}'|sed 's/^...//;$d;s/-/_/g'|nl|column -c 30|column -t|more -d
else
wget -qO - $sur|sed 's/||/\n /g;s/ /_/g;s/|/ /g'|sed '1d'|awk '{print $2}'|nl|column -c 30|column -t|more -d
fi;fi;
echo -e $purpuriu"Selectati numarul postului dorit sau" $rosu"r"$purpuriu"eveniti"";"$rosu "q"$purpuriu"uit" $rosu"i"$purpuriu"nregistrati"$rosu
read canal
if [[ "$canal" = "r" ]]; then break;fi;
if [[ "$canal" = "q" ]]; then clear ; exit 0; fi;
if [[ "$canal" = "i" ]]; then echo "Alegeti postul dorit pentru inregistrare:"
read canal2
clear
echo inregistrez... 
if [[ "$sur" = "cooltv" ]];then
adr2=`wget -qO - http://www.cool-tv.ro/m/|grep sop|sed 's/ /_/g;s/"/ /g;s/.gif//;$d'|awk '{print $2}'|sed -n "${canal2}p"`
soptest2=sop
numetv=`wget -qO - http://www.cool-tv.ro/m/|grep sop|sed 's/ /_/g;s/"/ /g;s/.gif//'|awk '{print $4}'|sed 's/^...//;$d;s/-/_/g'|sed -n "${canal2}p"`
else
adr2=`wget -qO - $sur | sed 's/||/\n /g;s/ /_/g;s/|/ /g'|sed '1d'|awk '{print $4}'|sed -n "${canal2}p"`
numetv=`wget -qO - $sur | sed 's/||/\n /g;s/ /_/g;s/|/ /g'|sed '1d'|awk '{print $2}'|sed -n "${canal2}p"`
soptest2=`wget -qO - $sur | sed 's/||/\n /g;s/ /_/g;s/|/ /g'|sed '1d'|awk '{print $4}'|sed -n "${canal2}p"|sed 's/:/ /g'|awk '{print $1}'`
pls2=`wget -qO - $sur | sed 's/||/\n /g;s/ /_/g;s/|/ /g'|sed '1d'|awk '{print $4}'|sed -n "${canal2}p"|sed 's/\./ /g'|awk '{ print $NF }'`
fi;
data=`date +_%F_%H-%M-%S`
echo $numetv
if [[ "$pls2" = "pls" ]]||[[ "$pls2" = "m3u" ]]; then list="-playlist";else list=" ";fi;
if [[ "$soptest2" = "sop" ]]; then 
$(sp-sc $adr2 8901 9901 &>/dev/null &); sleep 20; wait $(mplayer -cache 500 http://localhost:9901 -dumpstream -dumpfile $HOME/$numetv$data.mp4 &>/dev/null &);sleep 5;wait $(mplayer -nolirc -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry $coordonate -osdlevel 2 $HOME/$numetv$data.mp4); killall sp-sc mplayer;break 4;
else
$(mplayer $list $adr2 -dumpstream -dumpfile $HOME/$numetv$data.mp4 &>/dev/null & ); sleep 10 ; wait $(mplayer -msgcolor -nolirc -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry $coordonate -osdlevel 2 $HOME/$numetv$data.mp4); killall mplayer; break 4;
fi;fi;
############################
if [[ "$canal" = *[[:digit:]]* ]];then clear
if [[ "$sur" = "cooltv" ]];then
adr=`wget -qO - http://www.cool-tv.ro/m/|grep sop|sed 's/ /_/g;s/"/ /g;s/.gif//;$d'|awk '{print $2}'|sed -n "${canal}p"`
soptest=sop
else
adr=`wget -qO - $sur | sed 's/||/\n /g;s/ /_/g;s/|/ /g'|sed '1d'|awk '{print $4}'|sed -n "${canal}p"`
soptest=`wget -qO - $sur | sed 's/||/\n /g;s/ /_/g;s/|/ /g'|sed '1d'|awk '{print $4}'|sed -n "${canal}p"|sed 's/:/ /g'|awk '{print $1}'`
pls=`wget -qO - $sur | sed 's/||/\n /g;s/ /_/g;s/|/ /g'|sed '1d'|awk '{print $4}'|sed -n "${canal}p"|sed 's/\./ /g'|awk '{ print $NF }'`
fi;
if [[ "$pls" = "pls" ]]||[[ "$pls" = "m3u" ]]; then list="-playlist";else list=" ";fi;
echo -e $verde"procesez..."
if [[ "$soptest" = "sop" ]]; then 
$(sp-sc $adr 8901 9901 &>/dev/null &); sleep 10; wait $(mplayer -cache 500 -cache-min 20 -msglevel all=-1 -prefer-ipv4 -msgcolor -nolirc -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry $coordonate http://localhost:9901 &>/dev/null); killall sp-sc
else
mplayer -hardframedrop -cache 500 -cache-min 20 -msglevel cache=-1 -prefer-ipv4 -msgcolor -nolirc -ao alsa -vo xv,fbdev2, -xy $marime -zoom -geometry  $coordonate $list $adr
fi;fi;done;done


